name: PowerRanks
version: 0.0.5
main: me.winspeednl.pr.Main
authors: [winspeednl]
website: 'https://skyy.cc'
commands:
  powerranks:
    description: Main Command
  pr:
    description: Main Command
permissions:
  powerranks.cmd.help:
    default: true
  powerranks.cmd.check:
    default: true
  powerranks.cmd.set:
    default: op
